# Generated by Django 5.1.3 on 2024-11-26 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
