# Generated by Django 5.1.3 on 2024-11-29 23:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='next_execution_date',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recurringtransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='last_executed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringtransaction',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
