# Generated by Django 5.1.3 on 2024-11-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_account_number_alter_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default=452241540937, max_length=12, unique=True),
        ),
    ]
