# Generated by Django 5.1.3 on 2024-11-27 00:08

import accounts.models.account
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, default=accounts.models.account.random_account_number, max_length=12, unique=True),
        ),
    ]
